### ISSUE TITLE
Livestreaming silence causes client timeouts

### ISSUE THREAD

**Issue by s0ph0s-2** [xiph/flac#90] opened 2019-01-11 04:32 UTC
Hello! I’m a software developer for [XBN](https://xbn.fm), and we’re trying to improve our lossless streaming infrastructure. We’ve discovered that when live streaming OGG+FLAC to Icecast and digital silence occurs, stream clients misbehave. For instance, VLC will stop incrementing the play time counter, then time out and exit. MPV will play twice the length of the silence, once as it happens (empty buffer), and again after it ends (the silent data). To mitigate this problem we’ve been inserting dithering noise into our audio workflow, but this workaround somewhat defeats the point of lossless streaming. Digital silence can occur surprisingly often if using virtual audio devices, digital audio workflows (ie. S/PDIF) or when streaming any audio file that contains silence with no dither.

Through testing, we’ve figured out that the problem is caused by the CONSTANT subframe type waiting for the stream of identical samples to end before sending any data to clients. Using a test pipeline with the undocumented `--disable-constant-subframes` flag for `flac` seems to solve the timeout problems in the clients we tested. Of course, disabling the CONSTANT sub-frame type drastically reduces the efficiency of the codec in these cases, so it is a suboptimal solution. The easiest interim solution would be to make these private API functions (`FLAC__stream_encoder_disable_constant_subframes()` and company) public so that broadcast software can disable the feature when necessary, but since the problem isn’t inherent to the CONSTANT subframe optimization, there should be a better way to solve it.

Perhaps a “live” option could be added to the FLAC encoder (or perhaps the OGG muxer?) so that as digital silence occurs in an OGG+FLAC stream the encoder does not stop outputting data entirely. This would ensure that audio data continues to be streamed, preventing client buffers from emptying.

**Comment by ktmf01** [comment] 2021-11-11 20:49
As I understand (please correct if wrong)
- libFLAC is functioning properly
- When digital silence is fed to libFLAC, the FLAC bitrate becomes extremely low (44.1kHz stereo 16bit is 1.2kbit/s)
- This extremely low bitrate causes buffering issues
- This should be fixed by enforcing a certain minimum bitrate

> but since the problem isn’t inherent to the CONSTANT subframe optimization, there should be a better way to solve it.
I would say this problem is inherent to CONSTANT subframes, in that it compresses 'too good', bitrate gets too low. I just tested, when I use --disable-constant-subframes, bitrate goes up to 91kbit/s, which seems reasonable compared to the 600-1000kbit/s than an average FLAC stream uses.

I cannot think of another way to solve this but still stay FLAC compatible. There is no way to add padding to FLAC frames, so it is either the very low bitrate of constant subframes, or the next best which is fixed subframes with apparently a bitrate of 91kbit/s. You could also decrease the blocksize, but that would hurt the compression efficiency of non-silent blocks as well.

> The easiest interim solution would be to make these private API functions (`FLAC__stream_encoder_disable_constant_subframes()` and company) public so that broadcast software can disable the feature when necessary, but since the problem isn’t inherent to the CONSTANT subframe optimization, there should be a better way to solve it.

This function is already exported and available to programs using libFLAC, so I don't think there is much that can be done there.

Perhaps one of these solutions can help:
https://hydrogenaud.io/index.php?topic=87897.0
http://lists.xiph.org/pipermail/flac-dev/2014-May/004714.html

**Comment by rileywilddog** [comment] 2021-11-14 02:37
The workaround of disabling CONSTANT subframes effectively creates a minimum bitrate, but an ideal solution wouldn't require this (at least to this extent).
The symbol is at least exported in the binary, but having to patch the libFLAC headers to build with it feels a bit hacky :smile:

If we could figure out everywhere buffering is happening and force emission of data at some (<1s) interval, I think that could keep icecast and players happy with minimal overhead.

**Comment by ktmf01** [comment] 2021-11-14 18:16
The longer I think of it, the more I think disabling the use of constant subframes is the only possible solution. 

One could indeed try to check all buffers server-side, and make sure they are able to cope with an extremely low bitrate, but it is not possible to do this with client-side buffers. If there are indeed clients unable to cope with a bitrate as low as 1.2kbit/s (which wouldn't surprise me), increasing the bitrate is the only solution.

Increasing the bitrate cannot be done by just 'adding more data', 'forcing emission of data' or 'not stop outputting data'. The FLAC format has no room to add padding to the stream except at the very start of a file. So, not using constant subframes is probably the only way, because that way the encoder is forced to use subframe types that take more space.

To be able to use the function FLAC__stream_encoder_disable_constant_subframes() with current and previous FLAC releases, is to include include/share/private.h, or add this function prototype right below the includes:
> FLAC__bool FLAC__stream_encoder_disable_constant_subframes(FLAC__StreamEncoder *encoder, FLAC__bool value);

Perhaps this function should indeed be moved to a more general FLAC header file.

**Comment by ktmf01** [comment] 2021-12-01 20:40
Can perhaps someone with a working knowledge of FLAC web streaming try the changes in #264 to see whether it solves this problem?

**Comment by fritzbauer** [comment] 2021-12-01 21:35
Thank you for addressing this! 
I used to workaround it by [inserting some random values ](https://github.com/fritzbauer/ShoutVST/blob/master/ShoutVSTEncoderFLAC.cpp#L128) if silence is detected. Will try to compile FLAC with your changes and see if it works.

**Comment by fritzbauer** [comment] 2021-12-08 14:49
Confirmed this is working for me, when streaming to via an Icecast server, with the ShoutVST plugin which is using libshout and flac ogg stream encoding. Thank you so much!

**Comment by ktmf01** [comment] 2021-12-08 15:17
@fritzbauer I have no clue what a streaming toolchain looks like, so could you perhaps explain what you had to do to insert this modified libFLAC code? Was there a libflac.dll or libflac.so somewhere that you could replace, or did you have to recompile more?

**Comment by fritzbauer** [comment] 2021-12-08 15:55
Yes, exactly. I am not a cmake expert, but I tried to add FLAC streaming capabilities to the already existing ShoutVST plugin and this is done by cloning the flac repository and building it along with the whole plugin. 
The flac repository is cloned/updated when executing [sync.sh](https://github.com/fritzbauer/ShoutVST#linux-build-eg-ubuntu) in the build process. So I just checked out your branch after executing sync.sh, but before running the following (c)make steps.

**Closed** 2022-05-02 05:59 UTC

**Comment by ktmf01** [comment] 2022-05-02 06:03
For anyone listening in on this thread: with #264 libFLAC had gotten a `FLAC__stream_encoder_set_limit_min_bitrate()` function and the `flac` command line utility received a `--limit-min-bitrate` option to use it. When used, the minimum bitrate is raised to 1 bit/sample, so 48kbit/s for 48kHz material. It might take a few months before a release follows though.
