### ISSUE TITLE
Bug in CPU detection logic in libflac/cpu.c

### ISSUE THREAD

**Issue by sudo-rm-rf-oops** [xiph/flac#391] opened 2022-07-12 20:31 UTC
This bug report pertains to 1.3.2, but the problem looks to be still in there:

This:
```
void FLAC__cpu_info_x86(FLAC__uint32 level, FLAC__uint32 *eax, FLAC__uint32 *ebx, FLAC__uint32 *ecx, FLAC__uint32 *edx)
{
#if defined _MSC_VER || defined __INTEL_COMPILER
	int cpuinfo[4];
	int ext = level & 0x80000000;
	__cpuid(cpuinfo, ext);
	if((unsigned)cpuinfo[0] >= level) {
#if FLAC__AVX_SUPPORTED
		__cpuidex(cpuinfo, ext, 0); /* for AVX2 detection */
#else
		__cpuid(cpuinfo, ext); /* some old compilers don't support __cpuidex */
#endif

		*eax = cpuinfo[0]; *ebx = cpuinfo[1]; *ecx = cpuinfo[2]; *edx = cpuinfo[3];

		return;
	}
#elif defined __GNUC__ && defined HAVE_CPUID_H
	FLAC__uint32 ext = level & 0x80000000;
	__cpuid(ext, *eax, *ebx, *ecx, *edx);
	if (*eax >= level) {
		__cpuid_count(level, 0, *eax, *ebx, *ecx, *edx);

		return;
	}
#endif
	*eax = *ebx = *ecx = *edx = 0;
}
```
is totally broken.  I replaced it with this:
```
void FLAC__cpu_info_x86(FLAC__uint32 level, FLAC__uint32 *eax, FLAC__uint32 *ebx, FLAC__uint32 *ecx, FLAC__uint32 *edx)
{
#if defined _MSC_VER || defined __INTEL_COMPILER
	FLAC__uint32 ext = level & ~0x80000000;					/* PaulS, 16Feb22 */
	FLAC__uint32 max_level = 0;

	if (ext > 0)											/* is this level supported? */
	{
		FLAC__uint32 eax2, ebx2, ecx2, edx2;
		FLAC__cpu_info_x86(0, &eax2, &ebx2, &ecx2, &edx2);
		max_level = eax2;
	}

	if (ext <= max_level)
	{
		int cpuinfo[4];
#if FLAC__AVX_SUPPORTED
		__cpuidex(cpuinfo, ext, 0); /* for AVX2 detection */
#else
		__cpuid(cpuinfo, ext);		/* some old compilers don't support __cpuidex */
#endif
		*eax = cpuinfo[0]; *ebx = cpuinfo[1]; *ecx = cpuinfo[2]; *edx = cpuinfo[3];
		return;
	}
#elif defined __GNUC__ && defined HAVE_CPUID_H
	FLAC__uint32 ext = level & ~0x80000000;					/* PaulS, 16Feb22 (untested) */
	FLAC__uint32 max_level = 0;

	if (ext > 0)											/* is this level supported? */
	{
		FLAC__uint32 eax2, ebx2, ecx2, edx2;
		FLAC__cpu_info_x86(0, &eax2, &ebx2, &ecx2, &edx2);
		max_level = eax2;
	}

	if (ext <= max_level)
	{
		FLAC__uint32 eax2, ebx2, ecx2, edx2;
		__cpuid_count(level, 0, eax2, ebx2, ecx2, edx2);
		*eax = eax2; *ebx = ebx2; *ecx = ecx2; *edx = edx2;
		return;
	}
#endif

	*eax = *ebx = *ecx = *edx = 0;
}
```
More details on request (if I can remember!).

**Comment by ktmf01** [comment] 2022-07-13 07:04
Can you explain what was 'totally broken'? Because I've compiled recent FLAC versions many times on MSVC (and I know there are people regularly compiling this through MSVC with the Intel C Compiler), so I would've expected to see or hear something, especially as FLAC 1.3.2 has been out there for 5 years already.

Looking at the patch it seems you're checking the highest implemented function? However, it seems this function is only ever called with 0 or 1 in FLAC, and it seems that there exists no processor that does support cpuid but not at least level 0 and 1? It also seems to me that this check would best be placed in a separate function.

Also, discussing patches and giving credit is much easier when you file them as a PR instead of as an issue. If you don't mind not getting proper credit for this fix we can continue this way, otherwise please send in a PR instead.

**Comment by ktmf01** [comment] 2022-07-13 20:38
> Focussing on the MSVC implementation, this test:
> 
> ```
> 	__cpuid(cpuinfo, ext);
> 	if((unsigned)cpuinfo[0] >= level) {
> ```
> 
> always fails. In consequence, the manufacturer ID string is interpreted as feature bits.

I don't see how this is wrong. __cpuid is [documented here](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-170). It says: 
> When the function_id argument is 0, cpuInfo[0] returns the highest available non-extended function_id value supported by the processor. The processor manufacturer is encoded in cpuInfo[1], cpuInfo[2], and cpuInfo[3].

Also, if the call fails, cpuinfo[1], cpuinfo[2] and cpuinfo[3] aren't returned through *ebx, *ecx or *edx

**Comment by ktmf01** [comment] 2022-07-13 20:59
I think I understand what goes wrong now.
```
	if((unsigned)cpuinfo[0] >= level) {
#if FLAC__AVX_SUPPORTED
		__cpuidex(cpuinfo, ext, 0); /* for AVX2 detection */
#else
		__cpuid(cpuinfo, ext); /* some old compilers don't support __cpuidex */
#endif

		*eax = cpuinfo[0]; *ebx = cpuinfo[1]; *ecx = cpuinfo[2]; *edx = cpuinfo[3];

		return;
	}
```
I think replacing `ext` with `level` should do the trick. I will look it this again tomorrow.

**Comment by sudo-rm-rf-oops** [comment] 2022-07-13 21:13
Sorry, I was wrong on the detail, it's been a while since I looked at this.  But you're on the right lines there.  The complete faulty snippet is this:
```
	int cpuinfo[4];
	int ext = level & 0x80000000;
	__cpuid(cpuinfo, ext);
	if((unsigned)cpuinfo[0] >= level) {
```
and
```
	int ext = level & 0x80000000;
```
means that `ext` is always, in practise, zero, no matter what is passed in `level`.  So, close (me), but no cigar.  But same end result - the manufacturer id string is interpreted as feature bits, what fun!

**Comment by ktmf01** [comment] 2022-07-14 09:29
Yes, but that is how it is supposed to work. It checks either level 0 or level 0x80000000. See [the documentation](https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex?view=msvc-170)
```
            // Calling __cpuid with 0x80000000 as the function_id argument
            // gets the number of the highest valid extended ID.
            __cpuid(cpui.data(), 0x80000000);
            nExIds_ = cpui[0];
```

So, `int ext = level & 0x80000000;` determines whether a normal or extended ID is being used.

The problem is that this ext is reused in the lines below it, where we really want to query level. So, ext should be replaced with level in all but the first _cpuid call.

**Comment by sudo-rm-rf-oops** [comment] 2022-07-14 10:19
Oh, OK, I see what you mean.  Over to you then.  I don't think `level` is ever passed in with the high bit set, at present.

**Comment by ktmf01** [comment] 2022-07-16 10:00
Turns out this was already fixed in FLAC 1.3.3, see https://github.com/xiph/flac/commit/230cffe08ff0c965de2ce111afe4513286bfda89

**Comment by sudo-rm-rf-oops** [comment] 2022-07-16 10:38
Excellent.   Thanks, I'll upgrade.  As you say, a much better fix than mine.

**Comment by sudo-rm-rf-oops** [comment] 2022-07-17 12:29
PS: Sorry if I wasted your time with this.

**Comment by ktmf01** [comment] 2022-07-17 13:03
Not a problem, these bugs can be very tricky to find. I rather have them reported several times than not at all.

**Closed by ktmf01** 2022-07-17 13:03 UTC

**Comment by sudo-rm-rf-oops** [comment] 2022-07-17 13:57
Don't know if this will translate, but:👍🏼
