### ISSUE TITLE
Cannot build libaudiofile with flac 1.3.4

### ISSUE THREAD

**Issue by bertogg** [xiph/flac#327] opened 2022-04-22 23:45 UTC
Hello,

I apologize in advance if the problem is not in libflac, but after upgrading it from 1.3.3 to 1.3.4 we're having problems to build libaudiofile because the flac test fails. Here's the output of the test: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1008424

I'm not familiar with the code so I cannot really analyze it, but I bisected the changes in libflac and I saw that the problems started with commit https://github.com/xiph/flac/commit/159cd6c41a6ec17b36d74043c45a3aa64de90d5e. Reverting it makes the audiofile tests pass again.

**Comment by ktmf01** [comment] 2022-04-23 08:40
I just spent 90 minutes looking into this and it isn't any clearer to me yet. This will need some more time I'm afraid

**Comment by ktmf01** [comment] 2022-04-23 10:09
@enzo1982 Could you perhaps help out here? I don't fully understand how 159cd6c works.

I can't wrap my head around `if(decoder->protected_->state == FLAC__STREAM_DECODER_READ_FRAME) {`

As far as I know, `decoder->protected_->state` is pretty much always `FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC` when `seek_to_absolute_sample_` is called because that is how `FLAC__stream_decoder_process_single` leaves it ([see here](https://github.com/xiph/flac/blob/32d51aade69aa79b5c5f154bae95113a8e1775e1/src/libFLAC/stream_decoder.c#L2177)). I cannot find a way the code 159cd6c actually works, but according to #230 you tested this and found it working properly.

If I understand how `decoder->protected_->state` can be `FLAC__STREAM_DECODER_READ_FRAME` in `seek_to_absolute_sample_`, perhaps I can figure out how libaudiofile get there. Seeking in this state is something not currently covered by the test suite either it seems.

**Comment by enzo1982** [comment] 2022-04-23 16:15
It looks like `find_metadata_` can leave `decoder->protected_->state == FLAC__STREAM_DECODER_READ_FRAME`, so you could end up in this state after `FLAC__stream_decoder_process_until_end_of_metadata`. I don't really see another way to get to this state.

So yeah, looking at the code I now wonder myself how my patch could possibly work. I'll do some debugging and will report back. Likely only tomorrow, though.

I remember that when I wrote that code, it worked to reduce seek time when doing lots of seeking in files without seek tables. However, I cleaned up the code before creating the PR and it's possible that I broke something in the process. I tested the final patch too, but also implemented some optimizations in the code calling the FLAC routines in our codebase. It's possible that those optimizations made it look like the cleaned-up patch was still working when in fact it wasn't.

**Comment by ktmf01** [comment] 2022-04-24 08:28
@enzo1982 Many thanks for helping out. I find FLACs seeking code especially difficult to comprehend and debug, so I'm glad you want to take a look at it.

@bertogg I hope you still have the setup at hand you used to bisect the problem, could you perhaps try a possible fix for this problem? Could you change the following line of current flac master

https://github.com/xiph/flac/blob/32d51aade69aa79b5c5f154bae95113a8e1775e1/src/libFLAC/stream_decoder.c#L3094

to this

```
	if(decoder->protected_->state == FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC) {
```

and see whether it helps?

I think the problem is caused as follows
1. The libaudiofile test suite creates a headerless file (which are currently not covered by the testsuite)
2. libFLAC reads the headerless file, directly finds a sync code and goes into FLAC__STREAM_DECODER_READ_FRAME [here](https://github.com/xiph/flac/blob/32d51aade69aa79b5c5f154bae95113a8e1775e1/src/libFLAC/stream_decoder.c#L1375)
3. libaudiofile seeks to first sample. The code in 159cd6c triggers, and places a lower bound directly after the sync code read by step 2. This lower bound should have been placed 2 bytes earlier, at the first byte of the sync code
4. libFLAC cannot seek to the first sample, because it cannot find the sync code, as that is before the set lower bound

The code in 159cd6c assumes `FLAC__stream_decoder_get_decode_position` returns the position of the first byte of the frame belonging to `decoder->private_->samples_decoded`, but that is only true when `decoder->protected_->state == FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC`. When `decoder->protected_->state == FLAC__STREAM_DECODER_READ_FRAME`, `FLAC__stream_decoder_get_decode_position` can in theory return any byte of the frame.

**Comment by bertogg** [comment] 2022-04-24 21:54
Hey @ktmf01 I confirm that after changing the line that you suggested audiofile builds fine and all tests pass correctly. I tried with flac master and with v1.3.4. Thanks!

**Comment by enzo1982** [comment] 2022-04-24 22:51
I can confirm now that the check for `FLAC__STREAM_DECODER_READ_FRAME` is definitely wrong. That situation can only occur directly after `FLAC__stream_decoder_process_until_end_of_metadata` and thus my patch never worked as intended. This must have slipped in when cleaning up the patch for the PR.

However, simply replacing it with a check for `FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC` is not sufficient. After doing that, FLAC's `make check` fails at seek test # 30 (seeking to a random position after attempting to seek past the end).

I guess attempting to seek past the end of the stream invalidates some of the values used in my original patch and this must be accounted for. I'll take a closer look and will provide a working patch as soon as possible.

**Comment by ktmf01** [comment] 2022-04-25 05:45
If libFLAC seeks past the last sync code in the stream, it returns to `seek_to_absolute_sample_` with `decoder->private_->samples_decoded == 0`, see for example the code that checks for reaching end of stream: 

https://github.com/xiph/flac/blob/f304a4cf866ecc3ac747364dc278cfedb66369c2/src/libFLAC/stream_decoder.c#L3224

So perhaps we should change the code to this

```
	if(decoder->protected_->state == FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC &&
           decoder->private_->samples_decoded != 0) {
		if(target_sample < decoder->private_->samples_decoded) {
			if(FLAC__stream_decoder_get_decode_position(decoder, &upper_bound))
				upper_bound_sample = decoder->private_->samples_decoded;
		} else {
			if(FLAC__stream_decoder_get_decode_position(decoder, &lower_bound))
				lower_bound_sample = decoder->private_->samples_decoded;
		}
	}
 ```

**Comment by enzo1982** [comment] 2022-04-25 09:19
> So perhaps we should change the code to this
> ```
> 	if(decoder->protected_->state == FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC &&
>            decoder->private_->samples_decoded != 0) {
> ```

Yes, that code looks good. `seek_to_absolute_sample_` calls `FLAC__stream_decoder_flush` which sets `decoder->private_->samples_decoded` to `0`, but does not reset the read position. That's also the only place where `samples_decoded` is modified apart from `read_frame_`, so adding the check for `samples_decoded != 0` should be sufficient as a fix.

**Comment by bertogg** [comment] 2022-04-25 15:36
> So perhaps we should change the code to this
> 
> ```
> 	if(decoder->protected_->state == FLAC__STREAM_DECODER_SEARCH_FOR_FRAME_SYNC &&
>            decoder->private_->samples_decoded != 0) {

audiofile builds fine with this one as well.

**Closed** 2022-04-27 08:29 UTC
