### ISSUE TITLE
FLAC failed to build with "error LNK2019: unresolved external symbol ogg_sync_init referenced in function #ogg_sync_init$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by YangYang129** [xiph/flac#384] opened 2022-06-29 10:51 UTC
FLAC failed to build with "error LNK2019: unresolved external symbol ogg_sync_init referenced in function #ogg_sync_init$exit_thunk (EC Symbol)" with MSVC on Windows arm64ec. It can reproduce on latest version on master branch. Could you please help look at this issue?

**Repro steps:**
1. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
2. git clone https://github.com/xiph/flac F:\gitP\xiph\flac
3. cd F:\gitP\xiph\flac
4. git -C "F:\gitP\xiph\flac" apply f:\agent\_work\2\s\src\qa\suites\oss\patch\flac\flac_arm64ec_c7302_c1189.patch --ignore-space-change --ignore-whitespace --whitespace=nowarn
5.cd F:\gitP\Microsoft\vcpkg
6. bootstrap-vcpkg.bat 
7. vcpkg.exe install --recurse libogg --triplet arm64-windows --clean-after-build
8. cd F:\gitP\xiph\flac\build_arm64ec
9. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows -DBUILD_CXXLIBS=OFF -DBUILD_TESTING=OFF ..
10. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release FLAC.sln /t:Rebuild 

**Error log:**
[FLAC_build_fail.log](https://github.com/xiph/flac/files/9009789/FLAC_build_fail.log)

**Error info:**
```
 18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_init referenced in function #ogg_sync_init$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_clear referenced in function #ogg_sync_clear$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_reset referenced in function #ogg_sync_reset$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_buffer referenced in function #ogg_sync_buffer$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_wrote referenced in function #ogg_sync_wrote$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_sync_pageout referenced in function #ogg_sync_pageout$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_stream_pagein referenced in function #ogg_stream_pagein$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_stream_packetout referenced in function #ogg_stream_packetout$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_stream_init referenced in function #ogg_stream_init$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_stream_clear referenced in function #ogg_stream_clear$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_stream_reset referenced in function #ogg_stream_reset$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>FLAC.lib(ogg_decoder_aspect.obj) : error LNK2019: unresolved external symbol ogg_page_serialno referenced in function #ogg_page_serialno$exit_thunk (EC Symbol) [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
    18>F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\Release\decode_file.exe : fatal error LNK1120: 12 unresolved externals [F:\gitP\xiph\flac\build_arm64ec\examples\c\decode\file\decode_file.vcxproj]
```

**Comment by ktmf01** [comment] 2022-06-29 11:03
I'm unfamiliar with the vcpkg package manager. Actually, the rest of the toolchain is unfamiliar to me as well, so I'm not sure I can provide much help here.

Could you try building libogg alongside flac to see whether that solves the problem? This is done by downloading libogg sources, renaming the top directory to 'ogg' and moving it to the flac sources as a subdirectory. Simply this should work

```
git clone https://github.com/xiph/flac F:\gitP\xiph\flac
git clone https://github.com/xiph/ogg F:\gitP\xiph\flac\ogg
```

 See the [README](https://github.com/xiph/flac/blob/master/README) for more information. With this method, CMake integrates building of ogg into building flac. Maybe the results of building that way give more insight into this matter.

**Comment by ktmf01** [comment] 2022-07-06 15:07
@YangYang129 Can you please let me know whether your problem is solved with this?

**Comment by YangYang129** [comment] 2022-08-22 07:28
@ktmf01 According to your steps, above error does not repro. But repro other error" 24>F:\flac\src\libFLAC\stream_encoder_intrin_avx2.c : error C7302: <func:#0, Mod:F:\flac\src\libFLAC\stream_encoder_intrin_avx2.c> AVX types (__m256) are not currently supported in ARM64EC code"
Could you please help look at this issue?
[flac_C7302_msbuild.log](https://github.com/xiph/flac/files/9392193/flac_C7302_msbuild.log)

**Comment by ktmf01** [comment] 2022-08-22 07:37
It looks like the build is being configured for x86_64 while being build for ARM64. So, something is wrong in the cmake step. I suspect the problem is in the toolchain file. Could you perhaps take a look whether the toolchain file you're using is specifically meant for ARM64?

If you can't figure it out, please attach a cmake log. The build log you posted is of no help sadly.

**Comment by YangYang129** [comment] 2022-08-22 07:42
@ktmf01 I run `cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DOGG_LIBRARY=F:\ogg\build_arm64ec\Release -DOGG_INCLUDE_DIR=F:\ogg\include  ..`
-- The C compiler identification is MSVC 19.34.31819.96
-- The CXX compiler identification is MSVC 19.34.31819.96
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/Strawberry/perl/bin/pkg-config.bat (found version "0.26")
-- Found Ogg: F:/ogg/include (found version "")
-- Performing Test HAVE_MBSTATE
-- Performing Test HAVE_MBSTATE - Success
-- Performing Test DODEFINE_EXTENSIONS
-- Performing Test DODEFINE_EXTENSIONS - Success
-- Looking for byteswap.h
-- Looking for byteswap.h - not found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - found
-- Looking for intrin.h
-- Looking for intrin.h - found
-- Looking for fseeko
-- Looking for fseeko - not found
-- Performing Test HAVE_BSWAP16
-- Performing Test HAVE_BSWAP16 - Failed
-- Performing Test HAVE_BSWAP32
-- Performing Test HAVE_BSWAP32 - Failed
-- Performing Test HAVE_LANGINFO_CODESET
-- Performing Test HAVE_LANGINFO_CODESET - Failed
-- Performing Test HAVE_WERROR_FLAG
-- Performing Test HAVE_WERROR_FLAG - Failed
-- Performing Test HAVE_DECL_AFTER_STMT_FLAG
-- Performing Test HAVE_DECL_AFTER_STMT_FLAG - Failed
-- Performing Test HAVE_STACKREALIGN_FLAG
-- Performing Test HAVE_STACKREALIGN_FLAG - Failed
-- Performing Test HAVE_WEFFCXX_FLAG
-- Performing Test HAVE_WEFFCXX_FLAG - Failed
-- Looking for cpuid.h
-- Looking for cpuid.h - not found
-- Looking for sys/param.h
-- Looking for sys/param.h - not found
-- Looking for lround
-- Looking for lround - not found
-- Check CPU architecture is x64
-- Check CPU architecture is x64 - yes
-- Looking for a ASM_NASM compiler
-- Looking for a ASM_NASM compiler - C:/Program Files/NASM/nasm.exe
-- The ASM_NASM compiler identification is NASM
-- Found assembler: C:/Program Files/NASM/nasm.exe
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - not found
-- Looking for termios.h
-- Looking for termios.h - not found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find busybox, only basic tests are enabled
-- Configuring done
-- Generating done
-- Build files have been written to: F:/flac/build_arm64ec

**Comment by ktmf01** [comment] 2022-08-22 07:49
> @ktmf01 I run `cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DOGG_LIBRARY=F:\ogg\build_arm64ec\Release -DOGG_INCLUDE_DIR=F:\ogg\include ..`

As far as I know, this is not sufficient. A toolchain file seems to be missing. You mentioned one in your first post

>     8. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows -DBUILD_CXXLIBS=OFF -DBUILD_TESTING=OFF ..

Does using that help you?


> -- Check CPU architecture is x64
> -- Check CPU architecture is x64 - yes
> -- Looking for a ASM_NASM compiler
> -- Looking for a ASM_NASM compiler - C:/Program Files/NASM/nasm.exe
> -- The ASM_NASM compiler identification is NASM 
> -- Found assembler: C:/Program Files/NASM/nasm.exe

These lines confirm the build is being configured for x86_64 instead of ARM64

**Comment by YangYang129** [comment] 2022-08-22 08:08
@ktmf01 According to mentioned one in my first post
`8. cmake -G "Visual Studio 16 2019" -A ARM64EC -DCMAKE_SYSTEM_VERSION=10.0.22618.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows -DBUILD_CXXLIBS=OFF -DBUILD_TESTING=OFF ..`
and msbuild /m /p:Platform=ARM64EC /p:Configuration=Release FLAC.sln /t:Rebuild, repro "error LNK2019: unresolved external symbol ogg_sync_init referenced in function #ogg_sync_init$exit_thunk (EC Symbol)"

**Comment by ktmf01** [comment] 2022-08-22 08:21
That should've been solved by putting the ogg sources in the flac directory. Did you do that?

**Comment by ktmf01** [comment] 2022-08-22 08:37
Are you using flac sources from latest git or the 1.3.4 release?

**Comment by YangYang129** [comment] 2022-08-22 09:00
@ktmf01 I use latest version https://github.com/xiph/flac/commit/c90b3ea3c001785389b2f708621ba1e548276e3e on master branch. I add  && !defined(_M_ARM64EC) in line 40 of stream_encoder_intrin_avx2.c, this error" 24>F:\flac\src\libFLAC\stream_encoder_intrin_avx2.c : error C7302: <func:#0, Mod:F:\flac\src\libFLAC\stream_encoder_intrin_avx2.c> AVX types (__m256) are not currently supported in ARM64EC code" can not repro. And repro new error "FLAC.lib(stream_encoder.obj) : error LNK2001: unresolved external symbol #FLAC__lpc_compute_residual_from_qlp_coefficients_16_intrin_avx2 (EC Symbol)".

**Comment by ktmf01** [comment] 2022-08-22 09:05
You could add -DWITH_ASM=OFF to the cmake line, maybe that is enough to get this working. That would be a suboptimal solution however, as it also disables ARM64 assembler. Please let me know whether that works.

**Comment by YangYang129** [comment] 2022-08-22 09:19
@ktmf01 I add this option -DWITH_ASM=OFF and compiler pass. Thank you very much.

**Closed** 2022-08-22 09:33 UTC
