### ISSUE TITLE
Opencl acceleration?

### ISSUE THREAD

**Issue by Randrianasulu** [xiph/flac#545] opened 2023-02-14 03:12 UTC
I was looking at vhs-decode/ld-decode projects and they use flac for saving raw samples from high-speed ADC sampling analog video.

In theory there is support for cuda acceleration, but I am not fan of cuda.

So, there seems to be opencl encoder, yet it embedded in c# project ...

https://github.com/gchudov/cuetools.net/blob/master/CUETools.Codecs.FLACCL/flac.cl

I am not sure how useful this info in itself, but because there was no such issue I decided to create one.

**Comment by ktmf01** [comment] 2023-02-14 06:11
I don't understand what the issue is. You want a OpenCL accelerated FLAC encoder, there is one available, so what is the issue?

**Comment by Randrianasulu** [comment] 2023-02-14 08:34
@ktmf01 well, I can't easily compile this code on  termux? No idea if .net part work here, also their buildsystem is ...visual studio?

**Comment by ktmf01** [comment] 2023-02-14 11:47
So because you're unable to compile some code from another project, you're adding an 'issue' here that the code should be added to this project so you can compile it? Doesn't that seem a little strange? Maybe I still don't understand the issue?

**Comment by Randrianasulu** [comment] 2023-02-14 11:49
@ktmf01 guess there should be way to mark it as feature request?

**Comment by ktmf01** [comment] 2023-02-14 12:15
As far as I'm aware I don't have any OpenCL capable hardware at my disposal, so I am unable to implement this. Maybe you can try asking whether the good people over at CUETools could be tempted to port their build system to CMake, so you can build that instead?

**Comment by Randrianasulu** [comment] 2023-02-14 12:32
@ktmf01 yeah, I tried to run exe via mono runtime available in termux + clvk (opencl over Vulkan), got no devices, logged issue there and another issue at Mesa tracker, because llvmpipe also does not work

https://gitlab.freedesktop.org/mesa/mesa/-/issues/8289

**Comment by ktmf01** [comment] 2023-03-07 07:35
I close this as 'not planned'. I consider an OpenCL encoder out-of-scope for this project. Implementing this would be a lot of work for a small group of users, and there is already one available elsewhere. Also I don't have the hardware to do this.

**Closed by ktmf01** 2023-03-07 07:35 UTC
