### ISSUE TITLE
_FORTIFY_SOURCE breakage when cross-compiling with mingw-w64

### ISSUE THREAD

**Issue by bemoody** [xiph/flac#346] opened 2022-05-12 00:15 UTC
When cross-compiling flac using `gcc-mingw-w64-x86-64` on Debian 11, you'll get errors like:
```
/usr/bin/x86_64-w64-mingw32-ld: .libs/metadata_iterators.o:metadata_iterators.c:(.text+0x1125): undefined reference to `__memset_chk'
/usr/bin/x86_64-w64-mingw32-ld: .libs/metadata_iterators.o:metadata_iterators.c:(.text+0x150a): undefined reference to `__memset_chk'
/usr/bin/x86_64-w64-mingw32-ld: .libs/metadata_iterators.o:metadata_iterators.c:(.text+0x187e): undefined reference to `__memset_chk'
```
(Cross-compiling on Debian 10 doesn't have this issue.)

This is ultimately a bug in the mingw-w64 headers/libraries; however, the current version of `ax_add_fortify_source.m4` seems needlessly fragile.

An updated version of `ax_add_fortify_source.m4` was released in 2019, to try to work around this:
https://www.gnu.org/software/autoconf-archive/ax_add_fortify_source.html
Unfortunately, the new version still doesn't work on Debian 11 (gcc is just too clever.)

I'm not sure where to report bugs in autoconf-archive macros, and I'll try to figure that out, but wanted to remark on this here in case there is an easy workaround for flac.  (Aside from manually running `sed s/-D_FORTIFY_SOURCE=2// -i $(find . -name Makefile)`.)

**Comment by ktmf01** [comment] 2022-05-12 05:19
Are you compiling from the latest git master or from the 1.3.4 tarball? This should have been fixed already in git.

**Comment by bemoody** [comment] 2022-05-12 16:52
Hmm.  Yes, I was using flac-1.3.4, didn't realize this was already addressed in git.  Something else funky happens, though, with git master:
```
$ git clone https://github.com/xiph/flac
[...]
$ cd flac
$ ./autogen.sh
[...]
$ ./configure --host=x86_64-w64-mingw32 --disable-cpplibs --disable-ogg
$ make -Csrc/libFLAC V=1
[...]
/bin/bash ../../libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc    -O3 -funroll-loops -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wnested-externs -Wshadow -Wundef -Wmissing-declarations -Winline  -Wdeclaration-after-statement -msse2 -fstack-protector-strong  -no-undefined -version-info 11:0:3   -o libFLAC.la -rpath /usr/local/lib bitmath.lo bitreader.lo bitwriter.lo cpu.lo crc.lo fixed.lo fixed_intrin_sse2.lo fixed_intrin_ssse3.lo float.lo format.lo lpc.lo lpc_intrin_sse2.lo lpc_intrin_sse41.lo lpc_intrin_avx2.lo lpc_intrin_vsx.lo lpc_intrin_neon.lo md5.lo memory.lo metadata_iterators.lo metadata_object.lo stream_decoder.lo stream_encoder.lo stream_encoder_intrin_sse2.lo stream_encoder_intrin_ssse3.lo stream_encoder_intrin_avx2.lo stream_encoder_framing.lo window.lo windows_unicode_filenames.lo    -lm -lssp 
libtool: link: rm -fr  .libs/libFLAC.a .libs/libFLAC.la .libs/libFLAC.lai

*** Warning: linker path does not have real file for library -lssp.
*** I have the capability to make that library automatically link in when
*** you link to this library.  But I can only do this if you have a
*** shared version of the library, which you do not appear to have
*** because I did check the linker path looking for a file starting
*** with libssp but no candidates were found. (...for file magic test)
*** The inter-library dependencies that have been dropped here will be
*** automatically added whenever a program is linked with this library
*** or is declared to -dlopen it.

*** Since this library must not contain undefined symbols,
*** because either the platform does not support them or
*** it was explicitly requested with -no-undefined,
*** libtool will only create a static version of it.
libtool: link: x86_64-w64-mingw32-ar cr .libs/libFLAC.a .libs/bitmath.o .libs/bitreader.o .libs/bitwriter.o .libs/cpu.o .libs/crc.o .libs/fixed.o .libs/fixed_intrin_sse2.o .libs/fixed_intrin_ssse3.o .libs/float.o .libs/format.o .libs/lpc.o .libs/lpc_intrin_sse2.o .libs/lpc_intrin_sse41.o .libs/lpc_intrin_avx2.o .libs/lpc_intrin_vsx.o .libs/lpc_intrin_neon.o .libs/md5.o .libs/memory.o .libs/metadata_iterators.o .libs/metadata_object.o .libs/stream_decoder.o .libs/stream_encoder.o .libs/stream_encoder_intrin_sse2.o .libs/stream_encoder_intrin_ssse3.o .libs/stream_encoder_intrin_avx2.o .libs/stream_encoder_framing.o .libs/window.o .libs/windows_unicode_filenames.o
libtool: link: x86_64-w64-mingw32-ranlib .libs/libFLAC.a
libtool: link: ( cd ".libs" && rm -f "libFLAC.la" && ln -s "../libFLAC.la" "libFLAC.la" )
[...]
```
A bug in libtool?  I do have these files installed:
```
-rwxr-xr-x 1 root root 136292 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-posix/libssp-0.dll
-rw-r--r-- 1 root root  11474 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-posix/libssp.a
-rw-r--r-- 1 root root   7924 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-posix/libssp.dll.a
-rw-r--r-- 1 root root    800 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-posix/libssp_nonshared.a
-rwxr-xr-x 1 root root 136292 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libssp-0.dll
-rw-r--r-- 1 root root  11474 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libssp.a
-rw-r--r-- 1 root root   7924 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libssp.dll.a
-rw-r--r-- 1 root root    800 Jun 12  2021 /usr/lib/gcc/x86_64-w64-mingw32/10-win32/libssp_nonshared.a
```

**Comment by ktmf01** [comment] 2022-05-12 20:19
Yes, I have the same problem on my Debian machine when cross-compiling. I don't know what the problem is, but using the latest mingw compiler toolchain on msys2 (on a Windows machine) I don't have this problem.

There is a work-around: edit libtool, change `deplibs_check_method=pass_all` instead of what configure figured out it should be.

**Comment by ktmf01** [comment] 2022-05-25 07:53
@bemoody Can I close this issue?

**Closed** 2022-06-23 19:52 UTC
